name: Python CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    container: python:3.6-slim-buster

    steps:
    - uses: actions/checkout@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Test with unittest
      run: make test
    - name: Lint with pylama
      run: make link
